# settings
# 打开的模式
enabled_mode = ["chrome"]
# 模式呼出键
mode_key = "tab"
menu_position = "top_center"
menu_style = """
    body {
        font-family: Menlo, monospace, JetBrainsMono Nerd Font;
        background-color: #24283bcf;
        color: white;
    }
    .menu-container {
        width: 100%;
        height: 100%;
    }

    .menu-item {
        font-size: 12px;
        padding: 2px 10px;
        line-height: 16px;
        color:rgb(156, 88, 196);
    }

    .hot-key {
        color: #9fe044;
        font-weight: bold;
    }

    .menu-value {
        color: #c0caf5;
    }

    h1 {
        color: #c0caf5;
        font-size: 14px;
        margin: 2px 10px;
    }
"""

[root]
showTimeout = 3      # 自动隐藏时间，单位秒，默认5秒
name = "󰮫 My Leader"
# 显式指定菜单项顺序
order = ["a", "s", "o", "p", "q", "b", "x", "h"]
p = [
    "url",
    "raycast://extensions/raycast/clipboard-history/clipboard-history",
    "打开剪贴板历史记录",
]
q = ["hs", "hs.caffeinate.lockScreen()", "锁屏"]
b = ["open", "https://www.bilibili.com/", "哔哩哔哩", "tpzhao"]

[root.a]
name = "Apps"
order = ["c", "v", "b", "i", "w", "s"]
v = ["app", "Visual Studio Code"]
c = ["app", "Cursor"]
b = ["app", "Google Chrome"]
i = ["app", "iTerm"]
w = ["app", "Wechat"]
s = [
    "url",
    "raycast://extensions/Codely/google-chrome/search-tab",
    "打开Chrome搜索标签页",
]


[root.s]
name = "space"
silent = true
mode = "FLOAT"
showTimeout = 5
afterShow = "spoon.MyLeader.showNineSpace()"
afterHide = "spoon.MyLeader.hideNineSpace()"

# 显式指定子菜单顺序
order = ["u", "i", "o", "j", "k", "l", "m", ",", ".", "r", "s"]
1 = ["hotkey", [["ctrl", "shift"], "1"], "space 1"]
2 = ["hotkey", [["ctrl", "shift"], "2"], "space 2"]
3 = ["hotkey", [["ctrl", "shift"], "3"], "space 3"]
4 = ["hotkey", [["ctrl", "shift"], "4"], "space 4"]
5 = ["hotkey", [["ctrl", "shift"], "5"], "space 5"]
6 = ["hotkey", [["ctrl", "shift"], "6"], "space 6"]
7 = ["hotkey", [["ctrl", "shift"], "7"], "space 7"]
8 = ["hotkey", [["ctrl", "shift"], "8"], "space 8"]
9 = ["hotkey", [["ctrl", "shift"], "9"], "space 9"]
u = ["hotkey", [["ctrl", "shift"], "1"], "space 1"]
i = ["hotkey", [["ctrl", "shift"], "2"], "space 2"]
o = ["hotkey", [["ctrl", "shift"], "3"], "space 3"]
j = ["hotkey", [["ctrl", "shift"], "4"], "space 4"]
k = ["hotkey", [["ctrl", "shift"], "5"], "space 5"]
l = ["hotkey", [["ctrl", "shift"], "6"], "space 6"]
m = ["hotkey", [["ctrl", "shift"], "7"], "space 7"]
"," = ["hotkey", [["ctrl", "shift"], "8"], "space 8"]
"." = ["hotkey", [["ctrl", "shift"], "9"], "space 9"]
r = ["yabai", ["-m", "space", "--focus", "recent"], "recent space"]
s = ["sketchybar", ["--trigger", "yabai.clicked"], "switch space layout"]

[root.w]
name = "window"
order = ["h", "l", "r", "[", "]", "a", "d"]
h = ["yabai", ["-m", "window", "--focus", "west"], "focus west window"]
l = ["yabai", ["-m", "window", "--focus", "east"], "focus east window"]
r = ["yabai", ["-m", "window", "--focus", "recent"], "focus recent window"]
"[" = ["yabai", ["-m", "window", "--focus", "prev"], "focus prev window"]
"]" = ["yabai", ["-m", "window", "--focus", "next"], "focus next window"]
"a" = ["yabai", ["-m", "window", "--ratio", "abs:0.6"], "window 6:4"]
"b" = ["yabai", ["-m", "window", "--ratio", "abs:0.4"], "window 4:6"]

[root.t]
name = "move window to space"
silent = true
mode = "FLOAT"
showTimeout = 5
afterShow = "spoon.MyLeader.showNineSpace()"
afterHide = "spoon.MyLeader.hideNineSpace()"
u = ["hotkey", [['alt', 'shift'], '1'], "move to space 1"]
i = ["hotkey", [['alt', 'shift'], '2'], "move to space 2"]
o = ["hotkey", [['alt', 'shift'], '3'], "move to space 3"]
j = ["hotkey", [['alt', 'shift'], '4'], "move to space 4"]
k = ["hotkey", [['alt', 'shift'], '5'], "move to space 5"]
l = ["hotkey", [['alt', 'shift'], '6'], "move to space 6"]
m = ["hotkey", [['alt', 'shift'], '7'], "move to space 7"]
"," = ["hotkey", [['alt', 'shift'], '8'], "move to space 8"]
"." = ["hotkey", [['alt', 'shift'], '9'], "move to space 9"]

# h = ["window", "left"]
# l = ["window", "right"]
# u = ["window", "up"]
# j = ["window", "down"]
# f = ["window", "full"]

[root.o]
name = "open"
order = ["c", "w", "j"]
c = ["open", "https://chatgpt.com/", "chatGPT"]
w = ["open", "https://wiki.datatist.cn/", "wiki"]
j = ["open", "https://jira.datatist.cn/", "jira"]

[root.x]
name = "text"
1 = [
    "text",
    "k exec -it -n dev-wolf wolf-campaign-streaming-master0 -- bash",
    "进入straming master容器",
]
2 = ["text", "ps axu|grep java| awk '{print $2}'|xargs kill -9", "杀掉所有java进程"]

[root.h]
name = "hammerspoon"
r = ["hs", "hs.reload()", "重载配置"]
l = ["hs", "hs.openConsole()", "打开控制台"]
o = ["url", "https://www.hammerspoon.org/docs/", "hammerspoon文档"]

[modes.chrome]
name = "Google Chrome"
order = ["h", "l", "s"]
l = ["hotkey", [["ctrl"], "tab"], "切换到左侧标签页"]
h = ["hotkey", [["ctrl", "shift"], "tab"], "切换到右侧标签页"]
s = ["hotkey", [["shift", "cmd"], "a"], "搜索标签页"]
