# settings
# 打开的模式
enabled_mode = ["chrome"]
# 模式呼出键
mode_key = "tab"

[root]
show_timeout = 5   # 自动隐藏时间，单位秒，默认5秒
name = "My Leader"
# 显式指定菜单项顺序
order = ["a", "s", "o", "p", "q", "b", "x", "h"]
p = [
    "url",
    "raycast://extensions/raycast/clipboard-history/clipboard-history",
    "打开剪贴板历史记录",
]
q = ["hs", "hs.caffeinate.lockScreen()", "锁屏"]
b = ["open", "https://www.bilibili.com/", "哔哩哔哩", "tpzhao"]

[root.a]
name = "Apps"
order = ["c", "v", "b", "i", "w", "s"]
v = ["app", "Visual Studio Code"]
c = ["app", "Cursor"]
b = ["app", "Google Chrome"]
i = ["app", "iTerm"]
w = ["app", "Wechat"]
s = [
    "url",
    "raycast://extensions/Codely/google-chrome/search-tab",
    "打开Chrome搜索标签页",
]


[root.s]
name = "space"
# 显式指定子菜单顺序
order = ["1", "2", "3", "4", "5", "h", "l", "r"]
1 = ["hotkey", [["ctrl", "shift"], "1"], "space 1"]
2 = ["hotkey", [["ctrl", "shift"], "2"], "space 2"]
3 = ["hotkey", [["ctrl", "shift"], "3"], "space 3"]
4 = ["hotkey", [["ctrl", "shift"], "4"], "space 4"]
5 = ["hotkey", [["ctrl", "shift"], "5"], "space 5"]
r = ["yabai", ["-m", "space", "--focus", "recent"], "recent space"]
h = ["yabai", ["-m", "space", "--focus", "prev"], "prev space"]
l = ["yabai", ["-m", "space", "--focus", "next"], "next space"]

[root.w]
name = "window"
order = ["h", "l", "l", "r", "[", "]"]
h = ["yabai", ["-m", "window", "--focus", "west"], "focus west window"]
l = ["yabai", ["-m", "window", "--focus", "east"], "focus east window"]
r = ["yabai", ["-m", "window", "--focus", "recent"], "focus recent window"]
"[" = ["yabai", ["-m", "window", "--focus", "prev"], "focus prev window"]
"]" = ["yabai", ["-m", "window", "--focus", "next"], "focus next window"]

# h = ["window", "left"]
# l = ["window", "right"]
# u = ["window", "up"]
# j = ["window", "down"]
# f = ["window", "full"]

[root.o]
name = "open"
order = ["c", "w", "j"]
c = ["open", "https://chatgpt.com/", "chatGPT"]
w = ["open", "https://wiki.datatist.cn/", "wiki"]
j = ["open", "https://jira.datatist.cn/", "jira"]

[root.x]
name = "text"
1 = [
    "text",
    "k exec -it -n dev-wolf wolf-campaign-streaming-master0 -- bash",
    "进入straming master容器",
]
2 = ["text", "ps axu|grep java| awk '{print $2}'|xargs kill -9", "杀掉所有java进程"]

[root.h]
name = "hammerspoon"
r = ["hs", "hs.reload()", "重载配置"]
l = ["hs", "hs.openConsole()", "打开控制台"]

[modes.chrome]
name = "Google Chrome"
order = ["h", "l", "s"]
l = ["hotkey", [["ctrl"], "tab"], "切换到左侧标签页"]
h = ["hotkey", [["ctrl", "shift"], "tab"], "切换到右侧标签页"]
# s = ["hotkey", [["shift", "cmd"], "a"], "搜索标签页"]
