# settings
# 打开的模式
enabled_mode = ["mouse"]

[root]
show_timeout = 5                  # 自动隐藏时间，单位秒，默认5秒
label = "My Leader"
# 显式指定菜单项顺序
order = ["v", "c", "t", "w"]

v = ["app", "Visual Studio Code"]
c = ["app", "Google Chrome"]
t = ["app", "iTerm"]

[root.w]
label = "window"
# 显式指定子菜单顺序
order = ["l", "r", "c", "f", "m", "u", "d"]
l = ["window", "left"]
r = ["window", "right"]
f = ["window", "fullscreen"]
m = ["window", "maximize"]
c = ["window", "center"]
u = ["window", "up"]
d = ["window", "down"]
